name: med_ddpm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.12.2=h06a4308_0
  - et_xmlfile=1.1.0=py38h06a4308_0
  - h5py=3.11.0=py38hbe37b52_0
  - hdf5=1.12.1=h2b7332f_3
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - krb5=1.21.3=h8a1dbc1_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcurl=8.14.1=h31d0fb7_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.24.3=py38h060ed82_1
  - openpyxl=3.1.5=py38h5eee18b_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h993c535_1
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - argparse==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - batchgenerators==0.21
      - beautifulsoup4==4.13.4
      - cachetools==5.5.2
      - certifi==2025.6.15
      - charset-normalizer==2.0.12
      - click==8.1.8
      - cycler==0.12.1
      - dataclasses==0.6
      - dataclasses-json==0.6.7
      - deprecated==1.2.18
      - dicom2nifti==2.6.0
      - dill==0.4.0
      - einops==0.6.1
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - fury==0.12.0
      - future==1.0.0
      - gdown==5.2.0
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - grpcio==1.70.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.0
      - humanize==4.10.0
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - linecache2==1.0.0
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - matplotlib==3.5.3
      - mdurl==0.1.2
      - medpy==0.5.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - networkx==3.1
      - nibabel==4.0.2
      - nnunet-customized==1.2
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - p-tqdm==1.4.2
      - packaging==25.0
      - pandas==2.0.3
      - pathos==0.3.4
      - pillow==10.4.0
      - pox==0.3.6
      - ppft==1.7.7
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydicom==2.4.4
      - pygltflib==1.16.4
      - pygments==2.19.2
      - pynrrd==1.1.3
      - pyparsing==3.1.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-gdcm==3.0.25
      - pytorch-fid==0.3.0
      - pytorch-wavelets==1.3.0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - requests==2.27.1
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - rt-utils==1.2.7
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.0.2
      - scipy==1.10.1
      - shellingham==1.5.4
      - simpleitk==2.5.0
      - six==1.16.0
      - soupsieve==2.7
      - sympy==1.13.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.19
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchio==0.18.86
      - torchvision==0.19.1+cu118
      - totalsegmentator==1.5.7
      - tqdm==4.67.1
      - traceback2==1.4.0
      - triton==3.0.0
      - typer==0.16.0
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - unittest2==1.1.0
      - urllib3==1.26.20
      - vtk==9.3.1
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - xvfbwrapper==0.2.10
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/li46460/miniconda3/envs/med_ddpm
